serverAddr = "61.164.246.152"
serverPort = 42855

[[proxies]]
name = "ssh"
type = "tcp"
localIp = "127.0.0.1"
localPort = 22
remotePort = 6000

[[proxies]]
name = "rdp"
type = "tcp"
localIp = "127.0.0.1"
localPort = 3389
remotePort = 7001

[[proxies]]
name = "srdp"
type = "tcp"
localIp = "127.0.0.1"
localPort = 3390
remotePort = 7002
