[common]
server_addr = "61.164.246.152"
server_port = 7000
#token = "your_secure_token_here"

# 可选：管理接口（本地热重载）
#web_server_addr = "127.0.0.1"
#web_server_port = 7400

[[proxies]]
name = "ssh"
type = "tcp"
local_ip = "127.0.0.1"
local_port = 22
remote_port = 6000

[[proxies]]
name = "srdp"
type = "tcp"
local_ip = "127.0.0.1"
local_port = 7002
